CREATE TABLE `activityLog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`action` varchar(128) NOT NULL,
	`entityType` varchar(64),
	`entityId` int,
	`details` json,
	`ipAddress` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `activityLog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `automationRules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`datasetId` int,
	`mapType` varchar(64),
	`scheduleType` enum('manual','daily','weekly','monthly') DEFAULT 'manual',
	`scheduleConfig` json,
	`isActive` boolean DEFAULT true,
	`lastRunAt` timestamp,
	`nextRunAt` timestamp,
	`runCount` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `automationRules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `datasets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`originalFilename` varchar(255) NOT NULL,
	`format` enum('SHP','ECW','DXF') NOT NULL,
	`fileKey` varchar(512) NOT NULL,
	`fileUrl` text NOT NULL,
	`geojsonKey` varchar(512),
	`geojsonUrl` text,
	`fileSizeBytes` bigint,
	`featureCount` int,
	`geometryType` varchar(64),
	`crs` varchar(128),
	`originalCrs` varchar(128),
	`bbox` json,
	`attributes` json,
	`status` enum('uploading','processing','ready','error') NOT NULL DEFAULT 'uploading',
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `datasets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `generatedMaps` (
	`id` int AUTO_INCREMENT NOT NULL,
	`requestId` int NOT NULL,
	`userId` int NOT NULL,
	`datasetId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`mapType` varchar(64) NOT NULL,
	`thumbnailKey` varchar(512),
	`thumbnailUrl` text,
	`pngKey` varchar(512),
	`pngUrl` text,
	`pdfKey` varchar(512),
	`pdfUrl` text,
	`geojsonKey` varchar(512),
	`geojsonUrl` text,
	`mapConfig` json,
	`legendData` json,
	`stats` json,
	`width` int DEFAULT 1200,
	`height` int DEFAULT 800,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `generatedMaps_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `mapRequests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`datasetId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`mapType` enum('choropleth','heatmap','proportional_symbol') NOT NULL,
	`attributeField` varchar(128),
	`classificationMethod` enum('equal_interval','quantile','natural_breaks','standard_deviation') DEFAULT 'quantile',
	`numClasses` int DEFAULT 5,
	`colorScheme` varchar(64) DEFAULT 'YlOrRd',
	`colorReverse` boolean DEFAULT false,
	`opacity` float DEFAULT 0.8,
	`strokeColor` varchar(32) DEFAULT '#ffffff',
	`strokeWidth` float DEFAULT 0.5,
	`showLegend` boolean DEFAULT true,
	`showLabels` boolean DEFAULT false,
	`labelField` varchar(128),
	`customOptions` json,
	`status` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`errorMessage` text,
	`priority` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `mapRequests_id` PRIMARY KEY(`id`)
);
